version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002" # Use port 5002 for the backend
    volumes:
      - ./backend/todos.db:/app/todos.db
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5001:3000" # Use port 5001 for the frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5002